# Generated by Django 3.1.1 on 2021-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goaltype',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('time-bound', 'Time-Bound'), ('count-bound', 'Count-Bound'), ('abstain-or-limit', 'Abstain-Or-Limit')], default='unspecified', max_length=20, verbose_name='Type'),
        ),
    ]
