# Generated by Django 3.1.1 on 2021-01-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
